name: Deveji - Firebase App Distribution Deploy

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
        default: "appbundle"
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      git_ref:
        required: false
        type: string
        default: "main"
    secrets:
      firebase_account_key:
        required: true
      firebase_app_id:
        required: true

jobs:
  deploy:
    name: Deveji - Firebase App Distribution Deploy
    runs-on: ${{inputs.runs_on}}
    steps:

    - name: 📚 Git Checkout
      uses: actions/checkout@v4.1.6
      with:
        ref: ${{inputs.git_ref}}

    - name: 📂 Create directory for build file
      run: mkdir -p outputs

    - name: 📦 Get Build from artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        name: ${{inputs.artifact_name}}
        path: outputs

        # find the build file in the outputs directory and save it to the env variable
        # use this style:
        # run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: 📂 Find build file
      run: echo "BUILD_FILE=$(find outputs -type f \( -name "*.apk" -o -name "*.aab" -o -name "*.ipa" \) -print -quit)" >> $GITHUB_ENV
  
    - name: 📲 Upload build to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{secrets.FIREBASE_DEV_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_DEV_ACCOUNT_KEY }}
        groups: deveji
        file: ${{ env.BUILD_FILE }}
        debug: true
